name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 0 * * *'  # Запускать каждый день в полночь по UTC
  workflow_dispatch:  # Разрешить запуск вручную

jobs:
  update-playlist:
    runs-on: ubuntu-latest  # Используем Ubuntu для выполнения

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Клонируем репозиторий

    - name: List files in the directory
      run: |
        ls -al  # Проверим, какие файлы есть в репозитории

    - name: Download new playlist file
      run: |
        curl -o playlist.m3u8 "http://3da3b664c40e.faststreem.org/playlists/uplist/330b506ddde9b49aae71820847bea623/playlist.m3u8"
        echo "File downloaded successfully."  # Проверка, что файл скачан

    - name: Verify file download
      run: |
        ls -al  # Смотрим, что файл действительно был скачан
        cat playlist.m3u8 | head -n 10  # Выводим первые 10 строк для проверки содержимого

    - name: Check git status
      run: |
        git status  # Проверим, есть ли изменения

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Force commit and push changes
      run: |
        git add playlist.m3u8  # Добавляем новый файл
        git commit -m "Обновление плейлиста IPTV" || echo "No changes to commit"  # Коммитим изменения
        git push origin main  # Пушим изменения в основную ветку (измените 'main' на вашу ветку, если нужно)
